os: linux
language: android
jdk: openjdk21

android:
  components:
    - tools
    - platform-tools
    - tools
    - extra-android-m2repository
env:
  global:
    - TARGET_VERSION=35
    - ANDROID_BUILD_TOOLS_VERSION=35.0.0
    - ANDROID_HOME=~/android-sdk

before_install:
  # commandlinetools-linux-11076708_latest.zip
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-35" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;35.0.0" --sdk_root=$ANDROID_HOME

before_script:
  - chmod +x gradlew
script:
  - ./gradlew assemble